name: RP2040

on: workflow_dispatch

jobs:
    RP2040:
        runs-on: ubuntu-22.04
        permissions:
            packages: write
            
        steps:
            - name: Fetch repo
              uses: actions/checkout@v3

            - name: Detect changes
              uses: dorny/paths-filter@v2
              id: change
              with:
                filters: |
                    file-change:
                        - Development/hardware/RP2040/Dockerfile
            
            - name: Get date
              run: echo t=$(date +"%Y%m%d") >> $GITHUB_ENV
            
            - name: Login to Github
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Setup QEMU
              uses: docker/setup-qemu-action@v2

            - name: Setup Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build image and publish
              uses: docker/build-push-action@v4
              with:
                context: Development/hardware/RP2040/
                file: Development/hardware/RP2040/Dockerfile
                platforms: linux/amd64,linux/arm64
                push: true
                tags: ghcr.io/resripper/rp2040-dev:${{ env.t }}
